name: minimart
description: A minimart test
version: 1.0.0+1
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  bloc: ^8.1.4
  cached_network_image: ^3.4.1
  dartz: ^0.10.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  flutter_switch: ^0.3.2
  freezed_annotation: ^3.0.0
  gap: ^3.0.1
  go_router: ^15.1.2
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.5.0
  riverpod_annotation: ^2.6.1
  shared_preferences: ^2.5.3
  skeletonizer: ^1.4.3
  toastification: ^3.0.2

dev_dependencies:
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  envied_generator: ^1.1.1
  flutter_test:
    sdk: flutter
  freezed: ^3.0.4
  go_router_builder: ^2.9.0
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3
  very_good_analysis: ^6.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - assets/fonts/
    - assets/svg/
    - assets/images/
